# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy all files from the current directory
COPY . .

# Install dependencies without running prepare scripts for faster install
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Set the entrypoint to run the built server
CMD ["node", "dist/index.js"]
